jobs:
- job: Build
  displayName: Build HTML Project
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '*'
      TargetFolder: '/mnt/php'
  - upload: $(Build.ArtifactStagingDirectory)
    artifact: drop
  
- deployment: VMDeploy
  displayName: web
  environment:
    name: testing machine
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
