
jobs:
- job: Build
  displayName: Build HTML Project
  steps:
  - task: CopyFilesOverSSH@0
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      sshEndpoint: 'testing machine'
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '*'
      TargetFolder: '/mnt/php'
  - upload: /mnt/php
    artifact: drop
  
- deployment: VMDeploy
  displayName: web
  environment:
    name: testing machine
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CopyFilesOverSSH@0
          displayName: 'Securely copy files to the remote machine'
          inputs:
            sshEndpoint: 'testing machine'
            sourceFolder: '$(System.DefaultWorkingDirectory)'
            contents: '*'
            targetFolder: /mnt/php/
