jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: testing machine
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
