
jobs:
- job: Build
  displayName: Build HTML Project
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '*'
      TargetFolder: '/mnt/php'
  - upload: /mnt/php
    artifact: drop
  
- deployment: VMDeploy
  displayName: web
  dependsOn: Build
  environment:
    name: testing machine
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CopyFiles@2
          displayName: 'Copy files to VM'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '*'
            TargetFolder: '/mnt/php'
        - upload: /mnt/php
          artifact: drop
        - script: echo my first deployment
        steps:
        - task: CopyFilesOverSSH@0
          displayName: 'Securely copy files to the remote machine'
          inputs:
            sshEndpoint: 'testing machine'
            sourceFolder: '$(System.DefaultWorkingDirectory)'
            contents: '*'
            targetFolder: /mnt/php/
